#!/bin/sh
# -*- Mode: Shell-script -*-
#
# init --- Initialise makefiles for a given platform.
#
# Copyright (c) 2015-2017 Paul Ward <asmodai@gmail.com>
#
# Author:     Paul Ward <asmodai@gmail.com>
# Maintainer: Paul Ward <asmodai@gmail.com>
# Created:    Mon,  9 Nov 2015 09:01:23 +0000 (GMT)
# Keywords:   
# URL:        not distributed yet
#
# {{{ License:
#
# This program is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public
# Licenseas published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any
# later version.
#
# This program isdistributed in the hope that it will be
# useful, but WITHOUT ANY  WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
# }}}
# {{{ Commentary:
#
# }}}

PLATFORM=

usage() {
    echo "Usage: $0 <platform>"
    echo ""
    echo "Where platform is one of:"
    echo "   nextstep     - Build for NEXTSTEP."
    echo "   openstep     - Build for OPENSTEP."
    echo "   wof          - Build for OPENSTEP with WOF."
    echo "   rhapsody     - Build for Rhapsody."
}

copy_makefiles()
{
    _pwd=`pwd`
    if [ -z ${PLATFORM} ]
    then
        echo "No platform.  Cannot copy makefiles."
        exit 3
    fi

    # Pay attention and don't delete Makefile.[hm]!
    rm ${_pwd}/Source/Makefile.p* 2>/dev/null
    ln -s ${_pwd}/Build/${PLATFORM}/Makefile.* ${_pwd}/Source/ 2>/dev/null

    echo "Done."
}

process() {
    echo "****************** NeXTconf Initialisation ******************"
    echo "* Building for ${PLATFORM}"
    echo "*"

    echo -n "* Copying makefiles... "
    copy_makefiles

    echo "*"
    echo "* Ready."
    echo "*************************************************************"

    # Yeah, I know.  But seriously, read this.
    if [ ! -f .yeah.I.read.it ]
    then
        open -o INSTALL.rtf
    fi
}

if [ $# -lt 1 ]
then
    usage
    exit 1
fi


case $1 in
  nextstep) PLATFORM="NEXTSTEP"             ;;
  openstep) PLATFORM="OPENSTEP"             ;;
  rhapsody) PLATFORM="Rhapsody"             ;;
  wof)      PLATFORM="WOF"                  ;;
  *)        echo "Unknown platform \"$1\""
            usage
            exit 2
            ;;
esac

process

# init ends here
# Local Variables: ***
# indent-tabs-mode: nil ***
# End: ***
